<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Azure.AI.DocumentIntelligence" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
		<PackageReference Include="Microsoft.SemanticKernel" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.InMemory" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Athena.Core\Athena.Core.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
