<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Athena.Core\Athena.Core.csproj" />
    <ProjectReference Include="..\Athena.Ingestion\Athena.Ingestion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.QueryParser" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
