<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Athena.Agent\Athena.Agent.csproj" />
    <ProjectReference Include="..\Athena.Ingestion\Athena.Ingestion.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>athena-recommendation-engine-web</UserSecretsId>
  </PropertyGroup>

</Project>
